name: Vercel Development Deployment
env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Vercel CLI
        run: npm install --global vercel@latest
      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=development --token=${{ secrets.VERCEL_TOKEN }}
      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}
      - name: Deploy Project Artifacts to Vercel
        run: vercel deploy --prebuilt -e NEXT_PUBLIC_API_URL=${{ secrets.SKIP_DEV_API }} --token=${{ secrets.VERCEL_TOKEN }} | tee output.txt
      - name: Get deployment URL
        run: |
          DEPLOYMENT_URL=$(tail -n 1 output.txt)
          echo "DEPLOYMENT_URL=$DEPLOYMENT_URL" >> $GITHUB_ENV
      - name: Create an alias
        run: vercel alias -S skip-protocol --token=${{ secrets.VERCEL_TOKEN }} $DEPLOYMENT_URL dev.ibc.fun
